let contIconSearch = document.getElementById('contIconSearch')
let SearchBox = document.getElementById('SearchBox')

/*========== Obtener los años por ID ==========*/
// let year1927 = document.getElementById('year1927').style.display = "none"
// // let year1928 = document.getElementById('year1928').style.display = "block"
// let year1929 = document.getElementById('year1929').style.display = "none"
// let year1931 = document.getElementById('year1931').style.display = "none"
// let year1932 = document.getElementById('year1932').style.display = "none"
// let year1936 = document.getElementById('year1936').style.display = "none"
// let year1937 = document.getElementById('year1937').style.display = "none"
// let year1938 = document.getElementById('year1938').style.display = "none"
// let year1940 = document.getElementById('year1940').style.display = "none"
// let year1941 = document.getElementById('year1941').style.display = "none"
// let year1945 = document.getElementById('year1945').style.display = "none"
// let year1947 = document.getElementById('year1947').style.display = "none"
// let year1951 = document.getElementById('year1951').style.display = "none"
// let year1952 = document.getElementById('year1952').style.display = "none"
// let year1953 = document.getElementById('year1953').style.display = "none"
// let year1958 = document.getElementById('year1958').style.display = "none"
// let year1959 = document.getElementById('year1959').style.display = "none"
// let year1960 = document.getElementById('year1960').style.display = "none"
// let year1962 = document.getElementById('year1962').style.display = "none"
// let year1963 = document.getElementById('year1963').style.display = "none"
// let year1965 = document.getElementById('year1965').style.display = "none"
// let year1966 = document.getElementById('year1966').style.display = "none"
// let year1967 = document.getElementById('year1967').style.display = "none"
// let year1968 = document.getElementById('year1968').style.display = "none"
// let year1969 = document.getElementById('year1969').style.display = "none"
// let year1970 = document.getElementById('year1970').style.display = "none"
// let year1971 = document.getElementById('year1971').style.display = "none"
// let year1972 = document.getElementById('year1972').style.display = "none"
// let year1973 = document.getElementById('year1973').style.display = "none"
// let year1974 = document.getElementById('year1974').style.display = "none"
// let year1975 = document.getElementById('year1975').style.display = "none"
// let year1976 = document.getElementById('year1976').style.display = "none"
// let year1978 = document.getElementById('year1978').style.display = "none"
// let year1979 = document.getElementById('year1979').style.display = "none"
// let year1980 = document.getElementById('year1980').style.display = "none"
// let year1981 = document.getElementById('year1981').style.display = "none"
// let year1982 = document.getElementById('year1982').style.display = "none"
// let year1983 = document.getElementById('year1983').style.display = "none"
// let year1984 = document.getElementById('year1984').style.display = "none"
// let year1985 = document.getElementById('year1985').style.display = "none"
// let year1986 = document.getElementById('year1986').style.display = "none"
// let year1987 = document.getElementById('year1987').style.display = "none"
// let year1988 = document.getElementById('year1988').style.display = "none"
// let year1989 = document.getElementById('year1989').style.display = "none"
// let year1991 = document.getElementById('year1991').style.display = "none"
// let year1993 = document.getElementById('year1993').style.display = "none"
// let year1994 = document.getElementById('year1994').style.display = "none"
// let year1995 = document.getElementById('year1995').style.display = "none"
// let year1996 = document.getElementById('year1996').style.display = "none"
// let year1997 = document.getElementById('year1997').style.display = "none"
// let year1998 = document.getElementById('year1998').style.display = "none"
// let year1999 = document.getElementById('year1999').style.display = "none"
// let year2000 = document.getElementById('year2000').style.display = "none"
// let year2001 = document.getElementById('year2001').style.display = "none"
// let year2002 = document.getElementById('year2002').style.display = "none"
// let year2003 = document.getElementById('year2003').style.display = "none"
// let year2004 = document.getElementById('year2004').style.display = "none"
// let year2005 = document.getElementById('year2005').style.display = "none"
// let year2006 = document.getElementById('year2006').style.display = "none"
// let year2007 = document.getElementById('year2007').style.display = "none"
// let year2008 = document.getElementById('year2008').style.display = "none"
// let year2009 = document.getElementById('year2009').style.display = "none"
// let year2009Two = document.getElementById('year2009Two').style.display = "none"
// let year2015 = document.getElementById('year2015').style.display = "none"


/*==========BUSQUEDA==========*/
// let show = document.querySelectorAll('show')

let lists = document.querySelectorAll('.item')
let slide = document.getElementById('slide')
